name: Get User Data

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  schedule:
    - cron: '30 */6 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: lts/*

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm


      - name: Set beijing TimeZone
        uses: szenius/set-timezone@v1.2 # 设置虚拟环境的时区，可更改时区
        with:
          timezoneLinux: 'Asia/Shanghai'
          timezoneMacos: 'Asia/Singapore'

      - name: Install dependencies
        run: pnpm install

      - name: Generator Github User Data
        run: GITHUB_API_TOKEN=${{secrets.API_TOKEN}} pnpm run build:data

      - name: 'Commit'
        uses: EndBug/add-and-commit@v10
        with:
          author_name: lonewolfyx
          author_email: olddrivero.king@qq.com
          message: 'fix: update user data'
          add: '.'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
